### ISSUE TITLE
lsf ls_getentitlementinfo issue

### ISSUE THREAD

**Issue by kevinVervier** [kevinVervier/metagm#1]
lsid: ls_getentitlementinfo() failed: Failed in sending/receiving a message: Connection reset by peer
ls_gethostinfo(): Failed in sending/receiving a message: Connection reset by peer
Traceback (most recent call last):
  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/site-packages/farmpy/lsf.py", line 180, in _set_memory_units
    output = subprocess.check_output(self._lsadmin_cmd, shell=True).decode('utf-8').rstrip().split('\n')
  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'lsadmin showconf lim bc-26-2-08' returned non-zero exit status 255.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/bin/bsub.py", line 64, in <module>
    print(b)
  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/site-packages/farmpy/lsf.py", line 272, in __str__
    self._make_resources_string(),
  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/site-packages/farmpy/lsf.py", line 201, in _make_resources_string
    self._set_memory_units()
  File "/software/pathogen/external/apps/usr/local/Python-3.6.0/lib/python3.6/site-packages/farmpy/lsf.py", line 182, in _set_memory_units
    raise Error("Error getting lsf memory units using: lsadmin showconf lim " + socket.gethostname())
farmpy.lsf.Error: Error getting lsf memory units using: lsadmin showconf lim bc-26-2-08
Traceback (most recent call last):
  File "/nfs/team162/kv4/github/metagm/metagm/wrapper/metagm_classify.py", line 137, in <module>
    stringIDcmdBracken = stringIDcmdBracken + mglist.classify_bracken(args.BrackenDB, currentID) # take the list of Kraken jobs as an input
  File "/nfs/team162/kv4/github/metagm/metagm/sequences/MetagenomeList.py", line 83, in classify_bracken
    ' -i ' + metagenome.krakenReport + ' -r 150 -l ' + self.brackenRank + ' -o ' + self.outputDir + '/Bracken/' + metagenome.metagenomename + '_' + self.brackenRank + '.bracken"'], shell =True)
  File "/software/python-3.6.1/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/software/python-3.6.1/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['bsub.py  --done 7357297 --done 7357299 --done 7357301 --done 7357303 --done 7357305 --done 7357307 --done 7357309 --done 7357311 --done 7357313 --done 7357315 1 bracken "/nfs/team162/kv4/bin/Bracken/bracken -d MYDB -i XYZ.out -r 150 -l S -o XYZ_S.bracken"']' returned non-zero exit status 1.

**Comment by kevinVervier** [comment]
From IT Helpdesk:
regarding farm.py issue:
'Yes, but as that's a python library, you can modify it locally. It might be worth looking at updating that library, as the version you're using is now 2 years old. Martin Hunt (who wrote farmpy) no longer works at sanger, so I'm not sure how responsive he'll be to pull requests.
I think the actual cause may have been related to https://www.ibm.com/support/pages/lim-responds-slowly-when-running-lsf-command-after-many-hosts-are-powered-down-cluster as we closed a lot of hosts yesterday for the 115 downtime, but I'm not sure.'

Hopefully it will get better with farm4/5.

**Comment by kevinVervier** [comment]
Here is a fix for farm3: https://github.com/sanger-pathogens/Farmpy/pull/16

I got the confirmation that farm4/5 won't have this issue as they run this fix.
