### ISSUE TITLE
[Ben] module load and virtual environment

### ISSUE THREAD

**Issue by kevinVervier** [kevinVervier/metagm#5]
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f70bb413740 (most recent call first):
Aborted (core dumped)

**Comment by kevinVervier** [comment]
Probably needs to first load the modules, then the virtual environment.

**Comment by BenBeresfordJones** [comment]
I loaded modules first and then the local environment and ran metagm_build.py -h, I still get:

Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007fe8a98b1740 (most recent call first):
Aborted (core dumped)

If I deactivate the environment I get 
Traceback (most recent call last):
  File "/nfs/team162/kv4/github/metagm/metagm/wrapper/metagm_build.py", line 11, in <module>
    from metagm.sequences.BacterialGenome import BacterialGenome
  File "/nfs/team162/kv4/github/metagm/metagm/sequences/BacterialGenome.py", line 5, in <module>
    import Bio.SeqIO
ModuleNotFoundError: No module named 'Bio'

**Comment by kevinVervier** [comment]
I contacted pathInf to get insight

**Comment by kevinVervier** [comment]
Alright, so apparently I needed to create a new virtual environment for farm5...
Adding the following line to your .profile:
alias metagm_env_farm5='source /nfs/team162/kv4/bin/metagm_env_farm5/bin/activate'

Then, you need to load the module before running the virtual environment. It did work for me, give it a try.

**Comment by BenBeresfordJones** [comment]
I've just tried to use farm5 to run the metagm_build.py module again, this time with the updated aliases.

Still getting this: Traceback (most recent call last):
  File "/nfs/team162/kv4/github/metagm/metagm/wrapper/metagm_build.py", line 11, in <module>
    from metagm.sequences.BacterialGenome import BacterialGenome
  File "/nfs/team162/kv4/github/metagm/metagm/sequences/BacterialGenome.py", line 5, in <module>
    import Bio.SeqIO
ModuleNotFoundError: No module named 'Bio'

The command runs outside of job i.e. on command line, but the job runs out of memory...

Wondering if it might be related to my python dependencies, seeing as it works for you?

bsub.py 100 test_4128 'metagm_build.py --KrakenDB isolate_MAGS_high_metagm_batchfile.txt .'
Ran in this directory: /lustre/scratch118/infgen/team162/bb11/Kraken_databases/MOUSE/TEST_4128; if you want to test it out.

Sorry to bring this up again, but seeing as farm3 is closing I need to be able to run this on farm5...

Best wishes,
Ben

**Comment by BenBeresfordJones** [comment]
I've had a bit of a play around. It seems that I cannot import Bio from outside of your environment but I can within. Wondering if submitting the job means that it doesn't recognise the environment?

**Comment by kevinVervier** [comment]
I am running some tests where I source the venv inside the job.
You basically need to create a 'wrapper' script like this one:
```
#!/bin/bash

source /nfs/team162/kv4/bin/metagm_env_farm5/bin/activate 
metagm_build.py --KrakenDB /nfs/team162/kv4/Kraken1019/test.path /lustre/scratch118/infgen/team162/kv4/test_db_withvenv
```

and then run ` bsub.py 100 test_shortlist_withvenv 'sh wrapper_farm5.sh'`

So far it has not crashed, but I will keep you updated.
In the meantime @bb11-Cam it would be great if you also created this wrapper and try with your command.

**Comment by BenBeresfordJones** [comment]
Hi Kevin.

I ran the wrapper as you suggested:

Still getting the same issue.
Traceback (most recent call last):
  File "/nfs/team162/kv4/github/metagm/metagm/wrapper/metagm_build.py", line 11, in <module>
    from metagm.sequences.BacterialGenome import BacterialGenome
  File "/nfs/team162/kv4/github/metagm/metagm/sequences/BacterialGenome.py", line 5, in <module>
    import Bio.SeqIO
ModuleNotFoundError: No module named 'Bio'
