### ISSUE TITLE
Running non-gzipped single reads returns NonType

### ISSUE THREAD

**Issue by BenBeresfordJones** [kevinVervier/metagm#6]
bsub.py 1 -q basement classify 'metagm_classify.py --KrakenDB /Kraken --BrackenDB /Kraken -t 4 -q hugemem paths ./Kraken_test'

paths is a single column text file and looks like
/lustre/scratch118/infgen/team162/bb11/External_databases/mgp6153/test/mgm4537490.3.fq
/lustre/scratch118/infgen/team162/bb11/External_databases/mgp6153/test/mgm4538631.3.fq
/lustre/scratch118/infgen/team162/bb11/External_databases/mgp6153/test/mgm4538804.3.fq

Traceback (most recent call last):
  File "/nfs/team162/kv4/github/metagm/metagm/wrapper/metagm_classify.py", line 110, in <module>
    mg = Metagenome(metagenomename=os.path.basename(row[0]), metafastqfile1=row[0], metafastqfile2=None,queue=args.queue,nthreads=args.threads,memory=args.memory)
  File "/nfs/team162/kv4/github/metagm/metagm/sequences/Metagenome.py", line 51, in __init__
    if '.gz' in metafastqfile1 or '.gz' in metafastqfile2:
TypeError: argument of type 'NoneType' is not iterable
Traceback (most recent call last):
  File "/nfs/team162/kv4/github/metagm/metagm/wrapper/metagm_classify.py", line 110, in <module>
    mg = Metagenome(metagenomename=os.path.basename(row[0]), metafastqfile1=row[0], metafastqfile2=None,queue=args.queue,nthreads=args.threads,memory=args.memory)
  File "/nfs/team162/kv4/github/metagm/metagm/sequences/Metagenome.py", line 51, in __init__
    if '.gz' in metafastqfile1 or '.gz' in metafastqfile2:
TypeError: argument of type 'NoneType' is not iterable

**Comment by kevinVervier** [comment]
Could you try it now?
I fixed the test for calling a sample (single-end) zipped or not. Before, it was also checking the second fastq, which in single-end  case does not exit...
