### ISSUE TITLE
metagm_build --QC no module named 'Bio'

### ISSUE THREAD

**Issue by BenBeresfordJones** [kevinVervier/metagm#7]
I ran:
module load /nfs/users/nfs_k/kv4/modules/metagm
metagm_env
metagm_build.py --QC QC_input.txt ./QC

Error:
Traceback (most recent call last):
  File "/nfs/team162/kv4/github/metagm/metagm/wrapper/metagm_build.py", line 11, in <module>
    from metagm.sequences.BacterialGenome import BacterialGenome
  File "/nfs/team162/kv4/github/metagm/metagm/sequences/BacterialGenome.py", line 5, in <module>
    import Bio.SeqIO
ModuleNotFoundError: No module named 'Bio'

**Comment by kevinVervier** [comment]
Could you try on pcs5/farm3 without the module load part?

**Comment by kevinVervier** [comment]
Close this issue as it has the same fix as a previous one.
